### ISSUE TITLE
Allow weight == 100 to disable tests

### ISSUE THREAD

**Issue by johnluetke** [adrdilauro/angular-ab-tests#11]
I'd like to be able to specify a sum of weights equal to 100. This would allow me to weight the "old" version to 100%, effectively disabling the test without having to remove the `*abTestVersion` attributes from my markup.

**Comment by adrdilauro** [comment]
Hi @johnluetke, thank you for using `angular-ab-tests`!

You should be able to achieve your goal using the setter documented [here](https://github.com/adrdilauro/angular-ab-tests#manually-read--set-a-specific-version-during-runtime):

```typescript
this.abTestsService.setVersion('old');
```

In order for it to be sure that this is picked properly by the `abTestVersion` directive, you have to use the setter as soon as possible in `ngOnInit` of your app component; something like this:

```typescript
import { Component, OnInit } from '@angular/core';
import { AbTestsService } from 'angular-ab-tests';

@Component({
  // ...
})
export class AppComponent implements OnInit {
  constructor(private _abTestsService: AbTestsService) {}

  ngOnInit() {
    this._abTestsService.setVersion('old');
  }
}
```

Is this what you wanted to achieve? Please let me know if I am missing something

**Comment by johnluetke** [comment]
@adrdilauro Yes, that is a possible solution. I am more aiming for a "configuration" level change, vs needing to add code to the component to force a certain version temporarily

**Comment by adrdilauro** [comment]
Well, if you do something in `ngOnInit` of the app component, it could be considered as a configuration level change, because you are modifying only one line of code to affect the whole test.

Anyway, I think it should even work if you did the same thing in a module that you import in your core module. In the same `TestsModule` where in the docs it's suggested to do the tests configuration, you can create another standalone service, inject `AbTestsService` in it, and set the version there. It might work, I'll check it out when I have time

**Comment by johnluetke** [comment]
Thanks @adrdilauro. That would work as well, but ultimately I'm envisioning something that would live in the `AbTestOptions`

Would you be opposed to a PR that allows the sum of `weights` in `AbTestOptions` to equal 100?

**Comment by adrdilauro** [comment]
Hi @johnluetke, I saw the pull request, thanks.

I am sorry but I am super busy at the moment and I don't have time to do a new release (I did one just last week). Besides this, I don't think that it's worth doing a release for achieving something that can already be done in (I think) more appropriate ways.

I tested the configuration that you find in this commit: https://github.com/adrdilauro/angular-ab-tests/commit/a70691dd15e09fa1f8e7816775bdc62262e4b897. It works, and I think it's the most appropriate way to disable a test, leaving the markdown untouched.

If you are setting up tests in the way I suggested in the documentation, i.e. in a special `TestsModule` that is imported in the `CoreModule`, then, if you do the same thing as suggested in the commit above, you'll disable the test without touching anything in your application. You'd be changing only the content of that module, i.e., the configuration module for your tests.

If you are not setting up the tests in a separate module, I suggest you to do it because it's cleaner, it will take you very little effort to do that.

I apologise for not having time to do the release you wanted. 

I do agree that, in general, it would make sense me to have another look at the system of weights: when I developed weights, I did it almost arbitrarily, because I didn't know how effectively they could have been used in real-life tests. For instance, at the moment there is no way to explicitly set weights as fractions (1/3, 2/5, etc, they are all turned in integers which sum is 100: this might affect the result of a test, if somebody really needed to have a statistically precise division of, let's say, 2/5 + 1/5 + 3/5).

As soon as I'll have a bit of time I'll look into that too, but in the meanwhile you can already disable your tests using the method proposed above.

**Comment by adrdilauro** [comment]
Ah, regarding the commit I linked you: I forgot to mention that, of course, when you set up your tests in a real application, you have to replace the imports in the following way:

```typescript
import { AbTestsModule, AbTestOptions } from './modules/angular-ab-tests/module';
import { AbTestsService } from './modules/angular-ab-tests/service';
```

needs to be turned into

```typescript
import { AbTestsModule, AbTestOptions, AbTestsService } from 'angular-ab-tests';
```
